<?php
$events = [
    1 => ['title' => 'Independence Day', 'date' => '09 OCT 2025', 'time' => '10:00 AM - 2:00 PM', 'image' => 'nyabzgallery/indepe.jpg', 'gallery' => ['nyabzgallery/indepe.jpg', 'nyabzgallery/current.jpg'], 'location' => 'Nyabikoni Secondary School Grounds', 'download' => '', 'speakers' => [['name' => 'Hon. Janet Kataaha Museveni', 'title' => 'Minister of Education', 'photo' => 'nyabzgallery/HEADMASTER.jpg'], ['name' => 'Mr. John Doe', 'title' => 'Headmaster']], 'description' => "Uganda will celebrate the 62nd anniversary of its independence hosted by the northern district of Kitgum, highlighting the nation's unity and progress."],
    2 => ['title' => 'Induction Ceremony', 'date' => '15 JUL 2025', 'time' => '9:00 AM - 12:00 PM', 'image' => 'nyabzgallery/ceremony.jpg', 'gallery' => ['nyabzgallery/ceremony.jpg'], 'location' => 'Main Hall', 'download' => '', 'speakers' => [['name' => 'Ms. Jane Smith', 'title' => 'Senior Teacher']], 'description' => 'The school will hold an induction ceremony to officially welcome S.1 and S.5 learners, encouraging them to embrace the school community and its values.'],
    3 => ['title' => 'Pre-Mock Examinations', 'date' => '20 JUL 2025', 'time' => '', 'image' => 'nyabzgallery/exams.jpg', 'gallery' => ['nyabzgallery/exams.jpg'], 'location' => 'Examination Rooms', 'download' => '', 'speakers' => [], 'description' => 'Learners in S.4 and S.6 will sit their pre-mock examinations, preparing them for the upcoming mock exams with confidence and focus.'],
    4 => ['title' => 'Parent Visitation Day (Term III, 2025)', 'date' => '10 AUG 2025', 'time' => '', 'image' => 'nyabzgallery/VD.jpg', 'gallery' => ['nyabzgallery/VD.jpg'], 'location' => 'School Compound', 'download' => '', 'speakers' => [], 'description' => "Visitation day is scheduled for Sunday, 10 August 2025 starting at 8:00 AM. This is an opportunity to check on your child's progress and the school's environment."],
    5 => ['title' => 'UACE Results, 2025', 'date' => '15 MAR 2025', 'time' => '', 'image' => 'nyabzgallery/sucsess2.jpg', 'gallery' => ['nyabzgallery/sucsess2.jpg'], 'location' => 'Ministry of Education', 'download' => 'ADMISSION FORM FOR TERM I.docx', 'speakers' => [], 'description' => 'The Minister of Education and Sports will release the 2025 Uganda Advanced Certificate of Education results celebrating student achievements.'],
    6 => ['title' => 'UCE Results, 2025', 'date' => '22 MAR 2025', 'time' => '', 'image' => 'nyabzgallery/UCE RESULTS (2).jpg', 'gallery' => ['nyabzgallery/UCE RESULTS (2).jpg'], 'location' => 'State House', 'download' => '', 'speakers' => [], 'description' => 'The Minister of Education and Sports will release the 2025 Uganda Certificate of Education results at State House, recognizing student excellence.'],
    7 => ['title' => 'Chapel Times', 'date' => '28 JUL 2025', 'time' => '', 'image' => 'nyabzgallery/chapel3.jpg', 'gallery' => ['nyabzgallery/chapel3.jpg'], 'location' => 'School Chapel', 'download' => '', 'speakers' => [], 'description' => 'Students will gather for the Thanksgiving Mass on the Thirteenth Sunday in Ordinary Time, fostering spiritual growth.'],
    8 => ['title' => 'Parent Visitation Day (Term II, 2025)', 'date' => '01 JUL 2025', 'time' => '', 'image' => 'nyabzgallery/VD.jpg', 'gallery' => ['nyabzgallery/VD.jpg'], 'location' => 'School Compound', 'download' => '', 'speakers' => [], 'description' => 'Parents and guardians are invited to visitation day on Tuesday, 1 July 2025 starting at 8:00 AM.'],
    9 => ['title' => 'School Life', 'date' => '05 AUG 2025', 'time' => '', 'image' => 'nyabzgallery/school life.JPG', 'gallery' => ['nyabzgallery/school life.JPG'], 'location' => 'School Premises', 'download' => '', 'speakers' => [], 'description' => 'At Nyabikoni Secondary School, students enjoy a safe, inclusive environment with wide curricular and co-curricular opportunities.'],
];
